# Generated by Django 4.2.21 on 2025-05-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("levelupapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamer",
            name="display_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
